spring.application.name=girokonto-service

# Server-Port (Passend zur docker-compose)
server.port=9000

# DATENBANK-KONFIGURATION
# WICHTIG: Im Docker-Netzwerk muss 'girokonto-db' genutzt werden, nicht localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://girokonto-db:5432/girokonto}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# KAFKA KONFIGURATION
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}

# EIGENE Consumer-Gruppe für Girokonto (darf NICHT zahlungs-service sein)
spring.kafka.consumer.group-id=girokonto-service
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializer & Serializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JSON-Konfiguration
spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.value.default.type=com.bank.common.events.PaymentCompletedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=true


# Deaktiviert Header-Typ-Prüfung, falls Klassen in unterschiedlichen Packages liegen


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/myRealm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/myRealm

# FEHLERTOLERANZ BEIM START
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.admin.fail-fast=false

# LOGGING
logging.level.com.bank=DEBUG
logging.level.org.springframework=INFO
logging.level.org.apache.kafka=WARN
