services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093,CONTROLLER://:9094
      # Hier wird definiert, wie Kafka von wo erreicht wird:
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
 # KRaft benötigt kein KAFKA_ZOOKEEPER_CONNECT
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 5s
      timeout: 5s
      retries: 10


  girokonto-db:
    image: postgres:15
    environment:
      POSTGRES_DB: girokonto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - girokonto-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d girokonto"]
      interval: 10s
      timeout: 5s
      retries: 5

  kunden-db:
    image: postgres:15
    environment:
      POSTGRES_DB: inhaber
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - kunden-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d inhaber"]
      interval: 10s
      timeout: 5s
      retries: 5

  zahlung-db:
    image: postgres:15
    environment:
      POSTGRES_DB: zahlung
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - zahlung-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d zahlung"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloakdb
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpass
    ports:
      - "8081:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    ports:
      - "5435:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloakuser -d keycloakdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  girokonto-service:
    build: ./girokonto-service
    ports:
      - "9000:9000"
      - "5005:5005" # Debug-Port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://girokonto-db:5432/girokonto
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      KUNDEN_SERVICE_URL: http://kunden-service:9001/api/inhaber/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs
    depends_on:
      girokonto-db:
        condition: service_healthy
      kafka:
        condition: service_started
      keycloak:
        condition: service_started
      kunden-service:
        condition: service_started

  kunden-service:
    build: ./kunden-service
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kunden-db:5432/inhaber
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs
    depends_on:
      kunden-db:
        condition: service_healthy
      kafka:
        condition: service_started
      keycloak:
        condition: service_started

  zahlungs-service:
    build: ./zahlungs-service
    ports:
      - "9002:9002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://zahlung-db:5432/zahlung
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs
    depends_on:
      zahlung-db:
        condition: service_healthy
      kafka:
        condition: service_started
      keycloak:
        condition: service_started

volumes:
  girokonto-db-data:
  kunden-db-data:
  zahlung-db-data:
  keycloak-db-data: