spring.application.name=zahlungs-service

# Server-Port
server.port=9002

# DATENBANK-KONFIGURATION
# Im Docker-Netzwerk: Hostname 'zahlung-db' nutzen
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://zahlung-db:5432/zahlung}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# KAFKA KONFIGURATION
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}

# Consumer & Producer Einstellungen
spring.kafka.consumer.group-id=zahlungs-service
spring.kafka.consumer.auto-offset-reset=earliest

# DESERIALIZER/SERIALIZER (Müssen explizit gesetzt sein)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JSON-Konfiguration (Löst Typen- und Datumsprobleme)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.bank.common.events.PaymentRequestedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
# WICHTIG gegen den LocalDate Fehler:
spring.jackson.date-format=yyyy-MM-dd

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/myRealm/protocol/openid-connect/certs


# FEHLERTOLERANZ BEIM START
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.admin.fail-fast=false

# LOGGING
logging.level.com.bank=DEBUG
logging.level.org.springframework=INFO
logging.level.org.apache.kafka=WARN
